In [2]:

!pip install -U textblob 
#!python -m textblob.download_corpora
#!pip install -U textblob-aptagger
import textblob
import pandas as pd
from textblob import TextBlob

import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

Collecting textblob
  Downloading https://files.pythonhosted.org/packages/11/18/7f55c8be6d68ddc4036ffda5382ca51e23a1075987f708b9123712091af1/textblob-0.15.1-py2.py3-none-any.whl (631kB)
    100% |████████████████████████████████| 634kB 17.6MB/s
Requirement not upgraded as not directly required: nltk>=3.1 in /home/jupyterlab/conda/lib/python3.6/site-packages (from textblob) (3.3)
Requirement not upgraded as not directly required: six in /home/jupyterlab/conda/lib/python3.6/site-packages (from nltk>=3.1->textblob) (1.11.0)
distributed 1.21.8 requires msgpack, which is not installed.
Installing collected packages: textblob
Successfully installed textblob-0.15.1
[nltk_data] Downloading package punkt to /home/jupyterlab/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/jupyterlab/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/jupyterlab/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.

True

In [34]:
os.getcwd()
os.listdir()

['Twitter Sentiment.ipynb',
 '.jupyterlab',
 'data',
 '.ipynb_checkpoints',
 'Untitled.ipynb',
 'rstudio',
 'common']

In [38]:
twitter1_df = pd.read_csv('data/Captura_de_DiaMundialEnfermedadesRaras_-_Archive.csv',encoding='ISO-8859-1',sep=',')
linea1_df = pd.DataFrame(twitter1_df, columns=['text'])
twitter2_df = pd.read_csv('data/captura_de_SOMOSFEDER_-_Archive.csv',encoding='ISO-8859-1',sep=',')
linea2_df = pd.DataFrame(twitter2_df, columns=['text'])

lineas=pd.concat([linea1_df,linea2_df])

In [66]:
blob=TextBlob(str(lineas))

#contiene el tipo de palabra 
#NN: noun
#JJ: adjective
#IN: preposition
#VB_: verb 

tipos=blob.tags

#para traducir al ingles
#blob.translate(to="en") 

#nos quedamos sólo con los lexemas
#no estoy segura si está funcionando bien
for word, tag in tipos:
    word=word.lemmatize()

dir(tipos)
#tipos.len()
#print(tipos.sizeof())
tipos.count('0')

0

In [58]:
df = pd.DataFrame(blob.tags, columns=['word','tag'])


print(df.head())
print(df.tail())
#salen muy pocas palabras... hay algo raro

grupos=df.groupby('tag')
grupos.count()

palabras=df.groupby('word')
palabras.count()

             word  tag
0            text   NN
1               0   CD
2              RT  NNP
3               @  NNP
4  carlosmguevara   NN
        word  tag
573     rows  NNS
574        x  VBP
575        1   CD
576  columns  NNS
577        ]  VBP

                        tag
word
%                         1
//t.co/AwtbaJAxpP\nHoy    1
//t.co/M0                 1
0                         1
1                         2
10                        1
11                        1
12                        1
13                        1
14                        1
14:00                     1
15                        1
16                        1
17                        2
18                        1
19                        1
2                         1
20                        1
21                        1
22                        1
23                        1
24                        1
25                        1
26                        1
27                        1
28                        1
28804                     1
28805                     1
28806                     1
28807                     1
...                     ...
para                      3
parapaciente              2
pide                      1
por                       4
porque                    2
presente                  1
quiero                    1
redo                      1
resumen                   1
rows                      1
seis                      1
sin                       1
tal                       1
te                        6
text                      1
tienen                    1
un                        1
una                       1
unido                     3
unisevilla                2
valores                   1
vayas                     1
vergonzoso                1
x                         1
y                         1
Â¿AÃºn                    2
Â¿TodavÃ­a                3
Ãnete                    5
ðâ                   1
ð²ConcienciÃ©monos      1

[190 rows x 1 columns]

In [ ]:
#!!!!!hay que traducir los textos antes de calcular la polaridad y subjetividad
lineas['polarity'] = lineas.apply(lambda x: TextBlob(x['text']).sentiment.polarity, axis=1)
lineas['subjectivity'] = lineas.apply(lambda x: TextBlob(x['text']).sentiment.subjectivity, axis=1)